# Generated by Django 3.2.8 on 2022-06-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Pincode',
            field=models.IntegerField(null=True),
        ),
    ]
