# Generated by Django 3.2.8 on 2022-06-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='doctor.png', null=True, upload_to=''),
        ),
    ]
